on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd]
        goarch: [amd64, arm]
        exclude:
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.16
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.15"
        build_flags: -gcflags=all=-l
        ldflags: -w -s
        project_path: "./cmd/csgo_exporter"
        binary_name: "csgo_exporter"
        extra_files: LICENSE README.md
